Move tests into the `tests` directory & run tests on GH Actions
hackclub/burrow pull request #123
Opened 2023-06-29 04:52 UTC by sampoder

The successor to #121... rebasing is doing my head in but full steam ahead! This PR works towards resolving #82 & #60.

2023-07-01 14:12 UTC, conradev requested changes
We need to fix two things here:

- The test command should match the build command more. We should test all targets and features. We should also make explicit which targets we are testing in the matrix configuratio (i.e. the host target)

- The test command seemingly recompiles the crate, I'd be curious why it can't re-use the previous compile (might be for the above reason)

2023-07-03 16:15 UTC, sampoder commented
Let me look into recompilation, that'll speed things up a lot when removed!

2023-07-03 16:16 UTC, sampoder commented on .github/workflows/build-rust.yml
> +      run: cargo test
```suggestion
      run: cargo test --verbose --workspace --all-features --target ${{ join(matrix.targets, ' --target ') }}
```

@conradev is this what you're looking for?

2023-07-03 16:18 UTC, sampoder commented
> The test command seemingly recompiles the crate, I'd be curious why it can't re-use the previous compile (might be for the above reason)

Based on https://github.com/sagiegurari/cargo-make/issues/251, it seems like removing `cargo build [...]` and just doing `cargo test [...]` would achieve what we'd want.

2023-08-05 16:33 UTC, conradev approved these changes

2023-08-08 15:03 UTC, merged