initial burrow gtk
hackclub/burrow pull request #135
Opened 2023-07-01 17:29 UTC by reesericci

2023-07-01 17:36 UTC, conradev approved these changes

2023-07-01 17:36 UTC, conradev commented on burrow-gtk/README.md
Let's delete this file for now

2023-07-01 17:36 UTC, conradev commented on burrow-gtk/com.hackclub.Burrow.json
> +                    "url" : "file:///var/home/reesericci/Code"
Looks like we might want to make this relative somehow

2023-07-01 17:36 UTC, conradev commented on burrow-gtk/data/com.hackclub.Burrow.appdata.xml.in
> +	<id>com.hackclub.Burrow.desktop</id>
I've been using lowercase `b` so far, `com.hackclub.burrow`

2023-07-02 05:08 UTC, reesericci commented
Build succeeded & all comments resolved. Ready for review

2023-07-02 20:38 UTC, reesericci commented
Closes #83

2023-07-05 00:10 UTC, conradev reviewed
How do I build and test the app? Would it be possible to add that info to `GETTING_STARTED.md`?

Can we delete `burrow-gtk/README.md`?

2023-10-05 17:01 UTC, Muirrum requested changes

2023-10-05 17:01 UTC, Muirrum commented on burrow-gtk/src/config.rs
> +pub static PKGDATADIR: &str = "/app/share/burrow-gtk";
curious where these magic values come from?

2023-11-04 23:05 UTC, reesericci commented
I'm not really working on this anymore - someone can feel free to fork & send in a new PR if they want to work on it.

2023-11-04 23:05 UTC, closed without merging